CREATE TABLE `customers` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `personal_number` VARCHAR(255) UNIQUE,
    `phone_number` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
